### ISSUE TITLE
Estimating.js (Cannot read prop 'NAME' of undefined)

### ISSUE THREAD

**Issue by swarduda1** [UDATech/ConstructionOnlineBacklog#1]
**_DEVICE DATA**_
Browser version: Chrome 53.0
City: Delray Beach
Client IP address: 76.109.154.0
Country or region: United States
Device model: Other
Device type: Browser
Event time: 10/18/2016, 10:24:25 AM
Exception type: Cannot read property 'NAME' of undefined
Failed method: EstimateMemberMethods.Estimating.Estimate.generateTemplateObject_rsb
Handled at: unhandled
Operating system: Mac OS X 10.11
Operation Id: UDnAi
Operation name: /Budgets.aspx
Problem Id: Cannot read property 'NAME' of undefined at EstimateMemberMethods.Estimating.Estimate.generateTemplateObject_rsb
Sample Rate: 1
SDK version: javascript:1.0.3
Session Id: nEIbF
State or province: Florida
url: http://www.constructiononline.com/js/Estimating.js
User Id: emJYC

**_STACK TRACE**_

```
TypeError:
   at EstimateMemberMethods.Estimating.Estimate.generateTemplateObject_rsb (at EstimateMemberMethods.Estimating.Estimate.generateTemplateObject_rsb (http://www.constructiononline.com/js/Estimating.js:406:153): http://www.constructiononline.com/js/Estimating.js: 406)
   at Object.populateRSB (at Object.populateRSB (http://www.constructiononline.com/js/Estimating.js:4374:74): http://www.constructiononline.com/js/Estimating.js: 4374)
   at HTMLDivElement.<anonymous> (at HTMLDivElement.<anonymous> (http://www.constructiononline.com/js/Estimating.js:5159:33): http://www.constructiononline.com/js/Estimating.js: 5159)
   at HTMLDocument.dispatch (at HTMLDocument.dispatch (http://www.constructiononline.com/js/jquery-1.7.1.min.js:3:4351): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 3)
   at HTMLDocument.i (at HTMLDocument.i (http://www.constructiononline.com/js/jquery-1.7.1.min.js:3:328): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 3)
   at Object.trigger (at Object.trigger (http://www.constructiononline.com/js/jquery-1.7.1.min.js:3:3038): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 3)
   at HTMLDivElement.<anonymous> (at HTMLDivElement.<anonymous> (http://www.constructiononline.com/js/jquery-1.7.1.min.js:3:10497): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 3)
   at Function.each (at Function.each (http://www.constructiononline.com/js/jquery-1.7.1.min.js:2:11937): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 2)
   at each (at each (http://www.constructiononline.com/js/jquery-1.7.1.min.js:2:8483): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 2)
   at e.trigger (at e.trigger (http://www.constructiononline.com/js/jquery-1.7.1.min.js:3:10473): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 3)
```

[View this instance in the Azure portal](https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=c919a501-e1b8-41a2-ab70-7727367c8dd4&resourceGroup=Default-ApplicationInsights-CentralUS&componentName=ConstructionOnline&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%2522f6bbf020-9546-11e6-814d-4bdd39da9beb%2522%252C%2522name%2522%253A%2522Cannot%2520read%2520property%2520'NAME'%2520of%2520undefined%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522SubscriptionId%2522%253A%2522c919a501-e1b8-41a2-ab70-7727367c8dd4%2522%252C%2522ResourceGroup%2522%253A%2522Default-ApplicationInsights-CentralUS%2522%252C%2522Name%2522%253A%2522ConstructionOnline%2522%257D%252C%2522eventTime%2522%253A%25222016-10-18T15%253A24%253A25.268Z%2522%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222016-10-19T03%253A24%253A07.694Z%2522%252C%2522createdTime%2522%253A%2522Tue%2520Oct%252018%25202016%252010%253A32%253A03%2520GMT-0500%2520%28Central%2520Daylight%2520Time%29%2522%252C%2522isInitialTime%2522%253Atrue%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522context.operation.id%2522%253A%255B%2522UDnAi%2522%255D%257D%257D)
[View similar exceptions in this time range](https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=c919a501-e1b8-41a2-ab70-7727367c8dd4&resourceGroup=Default-ApplicationInsights-CentralUS&resourceName=ConstructionOnline&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522Cannot%2520read%2520property%2520'NAME'%2520of%2520undefined%2520at%2520EstimateMemberMethods.Estimating.Estimate.generateTemplateObject_rsb%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222016-10-19T03%253A24%253A25.268Z%2522%252C%2522createdTime%2522%253A%25222016-10-18T15%253A43%253A40.873Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D)

**Comment by bjenn** [comment]
fix is on beta
