### ISSUE TITLE
Estimating (AccountingIntegration is not defined)

### ISSUE THREAD

**Issue by swarduda1** [UDATech/ConstructionOnlineBacklog#2]
**_DEVICE DATA**_
Browser version: Chrome 53.0
City: Delray Beach
Client IP address: 76.109.154.0
Country or region: United States
Device model: Other
Device type: Browser
Event time: 10/18/2016, 10:24:07 AM
Exception type: AccountingIntegration is not defined
Failed method: <no_method>
Handled at: unhandled
Operating system: Mac OS X 10.11
Operation Id: UDnAi
Operation name: /Budgets.aspx
Problem Id: AccountingIntegration is not defined at <no_method>
Sample Rate: 1
SDK version: javascript:1.0.3
Session Id: nEIbF
State or province: Florida
url: http://www.constructiononline.com/js/ChangeOrder.js
User Id: emJYC

**_STACK TRACE**_

```
ReferenceError:
   at <no_method> (at http://www.constructiononline.com/js/ChangeOrder.js:1531:17: http://www.constructiononline.com/js/ChangeOrder.js: 1531)
   at <no_method> (at http://www.constructiononline.com/js/ChangeOrder.js:1242:17: http://www.constructiononline.com/js/ChangeOrder.js: 1242)
   at Object.success (at Object.success (http://www.constructiononline.com/js/Util.js:1298:21): http://www.constructiononline.com/js/Util.js: 1298)
   at n (at n (http://www.constructiononline.com/js/jquery-1.7.1.min.js:2:14784): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 2)
   at Object.fireWith [as resolveWith] (at Object.fireWith [as resolveWith] (http://www.constructiononline.com/js/jquery-1.7.1.min.js:2:15553): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 2)
   at w (at w (http://www.constructiononline.com/js/jquery-1.7.1.min.js:4:11395): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 4)
   at XMLHttpRequest.d (at XMLHttpRequest.d (http://www.constructiononline.com/js/jquery-1.7.1.min.js:4:17218): http://www.constructiononline.com/js/jquery-1.7.1.min.js: 4)
```

[View this instance in the Azure portal](https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=c919a501-e1b8-41a2-ab70-7727367c8dd4&resourceGroup=Default-ApplicationInsights-CentralUS&componentName=ConstructionOnline&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%2522f22bb9a0-9546-11e6-814d-4bdd39da9beb%2522%252C%2522name%2522%253A%2522AccountingIntegration%2520is%2520not%2520defined%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522SubscriptionId%2522%253A%2522c919a501-e1b8-41a2-ab70-7727367c8dd4%2522%252C%2522ResourceGroup%2522%253A%2522Default-ApplicationInsights-CentralUS%2522%252C%2522Name%2522%253A%2522ConstructionOnline%2522%257D%252C%2522eventTime%2522%253A%25222016-10-18T15%253A24%253A07.694Z%2522%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222016-10-19T03%253A24%253A07.694Z%2522%252C%2522createdTime%2522%253A%2522Tue%2520Oct%252018%25202016%252010%253A57%253A42%2520GMT-0500%2520%28Central%2520Daylight%2520Time%29%2522%252C%2522isInitialTime%2522%253Atrue%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522context.operation.id%2522%253A%255B%2522UDnAi%2522%255D%257D%257D)
[View similar exceptions in this time range](https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=c919a501-e1b8-41a2-ab70-7727367c8dd4&resourceGroup=Default-ApplicationInsights-CentralUS&resourceName=ConstructionOnline&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522AccountingIntegration%2520is%2520not%2520defined%2520at%2520%253Cno_method%253E%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222016-10-19T03%253A24%253A07.694Z%2522%252C%2522createdTime%2522%253A%25222016-10-18T15%253A58%253A04.804Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D)

**Comment by swarduda1** [comment]
Added AccountingIntegration reference to Budgets.aspx (needed for proper costing)
